# Generated by Django 5.0.6 on 2024-05-12 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Кодовой обозначение')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Depositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Почта')),
                ('telephone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('depositorPremium', 'Вкладчик с высоким рейтингом'), ('depositorNormal', 'Вкладчик с обычным рейтингом'), ('depositorGarbage', 'Вкладчик из черного списка')], max_length=20, verbose_name='Роль')),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='День рождения')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
            ],
            options={
                'verbose_name': 'Вкладчик',
                'verbose_name_plural': 'Вкладчики',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='Сумма')),
                ('annual_percentage', models.FloatField(default=0.0, verbose_name='Годовой процент')),
                ('dc', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата записи')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depositor')),
            ],
            options={
                'verbose_name': 'Вклад',
                'verbose_name_plural': 'Вклады',
            },
        ),
    ]
