# Generated by Django 5.0.6 on 2024-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositor',
            name='passport',
            field=models.CharField(default='', max_length=11, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='depositor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фото вкладчика'),
        ),
    ]
