# Generated by Django 5.0.6 on 2024-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_deposit_currency_alter_deposit_depositor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Кодовой обозначение'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='depositor',
            name='passport',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='Серия и номер паспорта'),
        ),
    ]
